# Generated by Django 6.0.3 on 2026-04-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication_sing",
                    models.BooleanField(
                        auto_created=True,
                        default=True,
                        help_text="Укажите признак публикации (булевое поле)",
                        verbose_name="Признак публикации",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_created=True,
                        blank=True,
                        help_text="Укажите дату создания поста",
                        null=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок поста",
                        max_length=200,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Введите контент блога", verbose_name="Содержимое"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Вставьте фото",
                        null=True,
                        upload_to="catalog/photo",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество просмотров",
                        verbose_name="Счетчик просмотров",
                    ),
                ),
            ],
        ),
    ]
