# Generated by Django 6.0.3 on 2026-04-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title", "content", "views_counter"],
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
            },
        ),
    ]
