# Generated by Django 6.0.3 on 2026-04-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="publication_sing",
        ),
        migrations.AddField(
            model_name="blog",
            name="is_publication",
            field=models.BooleanField(
                default=True,
                help_text="Укажите признак публикации (булевое поле)",
                verbose_name="Признак публикации",
            ),
        ),
    ]
