# Generated by Django 6.0.3 on 2026-04-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_blog_publication_sing_blog_is_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату создания поста",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
    ]
