# Generated by Django 6.0.3 on 2026-05-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Вставьте фото",
                null=True,
                upload_to="blog/photo",
                verbose_name="Фото",
            ),
        ),
    ]
